name: Native Compile for Releases

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle (Linux & macOS)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Run Compile
        run: ./gradlew clean packageWinX64 packageLinuxX64 packageMacM1 packageMacX64
        env:
          USERNAME: ${{ secrets.GITHUB_ACTOR }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: lwjgl3/build/distributions/launcher-package.zip
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: client/build/construo/winX64
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: client/build/construo/linuxX64
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: client/build/construo/macX64
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: client/build/construo/macM1
          token: ${{ secrets.GITHUB_TOKEN }}
