name: Native Compile for Artifacts

on:
  push:
    branches:
      - main
      - 'channels/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run Compile
        run: gradle clean packageWinX64 packageLinuxX64 packageMacM1 packageMacX64
        env:
          USERNAME: ${{ secrets.GITHUB_ACTOR }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: lwjgl3/build/construo/winX64/roast
          retention-days: 1

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: lwjgl3/build/construo/linuxX64/roast
          retention-days: 1

      - name: Upload macOS x64 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-x64
          path: lwjgl3/build/construo/macX64/roast
          retention-days: 1

      - name: Upload macOS M1 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-m1
          path: lwjgl3/build/construo/macM1/roast
          retention-days: 1
